// source: SittelleTypeOffice.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeTask_pb = require('./SittelleTypeTask_pb.js');
goog.object.extend(proto, SittelleTypeTask_pb);
goog.exportSymbol('proto.SittelleProtos.Company', null, global);
goog.exportSymbol('proto.SittelleProtos.Contract', null, global);
goog.exportSymbol('proto.SittelleProtos.Department', null, global);
goog.exportSymbol('proto.SittelleProtos.Employee', null, global);
goog.exportSymbol('proto.SittelleProtos.MonObjectSystem', null, global);
goog.exportSymbol('proto.SittelleProtos.ServiceOrganization', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.Employee = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.Employee, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.Employee.displayName = 'proto.SittelleProtos.Employee';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.Company = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.Company, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.Company.displayName = 'proto.SittelleProtos.Company';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.Department = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.Department.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.Department, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.Department.displayName = 'proto.SittelleProtos.Department';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.MonObjectSystem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.MonObjectSystem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.MonObjectSystem.displayName = 'proto.SittelleProtos.MonObjectSystem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.Contract = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.Contract, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.Contract.displayName = 'proto.SittelleProtos.Contract';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ServiceOrganization = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ServiceOrganization.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ServiceOrganization, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ServiceOrganization.displayName = 'proto.SittelleProtos.ServiceOrganization';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.Employee.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.Employee.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.Employee} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Employee.toObject = function(includeInstance, msg) {
  var f, obj = {
    position: jspb.Message.getFieldWithDefault(msg, 1, ""),
    officePhone: jspb.Message.getFieldWithDefault(msg, 2, ""),
    companyInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    personValue: (f = msg.getPersonValue()) && SittelleTypeTask_pb.Person.toObject(includeInstance, f),
    asContact: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.Employee}
 */
proto.SittelleProtos.Employee.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.Employee;
  return proto.SittelleProtos.Employee.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.Employee} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.Employee}
 */
proto.SittelleProtos.Employee.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPosition(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOfficePhone(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCompanyInd(value);
      break;
    case 4:
      var value = new SittelleTypeTask_pb.Person;
      reader.readMessage(value,SittelleTypeTask_pb.Person.deserializeBinaryFromReader);
      msg.setPersonValue(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAsContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.Employee.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.Employee.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.Employee} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Employee.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPosition();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOfficePhone();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCompanyInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getPersonValue();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SittelleTypeTask_pb.Person.serializeBinaryToWriter
    );
  }
  f = message.getAsContact();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional string position = 1;
 * @return {string}
 */
proto.SittelleProtos.Employee.prototype.getPosition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Employee} returns this
 */
proto.SittelleProtos.Employee.prototype.setPosition = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string office_phone = 2;
 * @return {string}
 */
proto.SittelleProtos.Employee.prototype.getOfficePhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Employee} returns this
 */
proto.SittelleProtos.Employee.prototype.setOfficePhone = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 company_ind = 3;
 * @return {number}
 */
proto.SittelleProtos.Employee.prototype.getCompanyInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Employee} returns this
 */
proto.SittelleProtos.Employee.prototype.setCompanyInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional Person person_value = 4;
 * @return {?proto.SittelleProtos.Person}
 */
proto.SittelleProtos.Employee.prototype.getPersonValue = function() {
  return /** @type{?proto.SittelleProtos.Person} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.Person, 4));
};


/**
 * @param {?proto.SittelleProtos.Person|undefined} value
 * @return {!proto.SittelleProtos.Employee} returns this
*/
proto.SittelleProtos.Employee.prototype.setPersonValue = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.Employee} returns this
 */
proto.SittelleProtos.Employee.prototype.clearPersonValue = function() {
  return this.setPersonValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.Employee.prototype.hasPersonValue = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool as_contact = 5;
 * @return {boolean}
 */
proto.SittelleProtos.Employee.prototype.getAsContact = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SittelleProtos.Employee} returns this
 */
proto.SittelleProtos.Employee.prototype.setAsContact = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.Company.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.Company.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.Company} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Company.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    caption: jspb.Message.getFieldWithDefault(msg, 2, ""),
    address: jspb.Message.getFieldWithDefault(msg, 3, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 4, ""),
    email: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.Company}
 */
proto.SittelleProtos.Company.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.Company;
  return proto.SittelleProtos.Company.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.Company} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.Company}
 */
proto.SittelleProtos.Company.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.Company.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.Company.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.Company} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Company.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.Company.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Company} returns this
 */
proto.SittelleProtos.Company.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string caption = 2;
 * @return {string}
 */
proto.SittelleProtos.Company.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Company} returns this
 */
proto.SittelleProtos.Company.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string address = 3;
 * @return {string}
 */
proto.SittelleProtos.Company.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Company} returns this
 */
proto.SittelleProtos.Company.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string phone = 4;
 * @return {string}
 */
proto.SittelleProtos.Company.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Company} returns this
 */
proto.SittelleProtos.Company.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string email = 5;
 * @return {string}
 */
proto.SittelleProtos.Company.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Company} returns this
 */
proto.SittelleProtos.Company.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.Department.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.Department.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.Department.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.Department} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Department.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    active: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    parentId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    caption: jspb.Message.getFieldWithDefault(msg, 5, ""),
    priority: jspb.Message.getFieldWithDefault(msg, 6, 0),
    monObjectInd: jspb.Message.getFieldWithDefault(msg, 7, 0),
    additionalParamListList: jspb.Message.toObjectList(msg.getAdditionalParamListList(),
    SittelleTypeTask_pb.AdditionalParam.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.Department}
 */
proto.SittelleProtos.Department.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.Department;
  return proto.SittelleProtos.Department.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.Department} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.Department}
 */
proto.SittelleProtos.Department.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPriority(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMonObjectInd(value);
      break;
    case 8:
      var value = new SittelleTypeTask_pb.AdditionalParam;
      reader.readMessage(value,SittelleTypeTask_pb.AdditionalParam.deserializeBinaryFromReader);
      msg.addAdditionalParamList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.Department.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.Department.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.Department} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Department.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getActive();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getParentId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getMonObjectInd();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getAdditionalParamListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      SittelleTypeTask_pb.AdditionalParam.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.Department.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.SittelleProtos.Department.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool active = 3;
 * @return {boolean}
 */
proto.SittelleProtos.Department.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setActive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string parent_id = 4;
 * @return {string}
 */
proto.SittelleProtos.Department.prototype.getParentId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setParentId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string caption = 5;
 * @return {string}
 */
proto.SittelleProtos.Department.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 priority = 6;
 * @return {number}
 */
proto.SittelleProtos.Department.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 mon_object_ind = 7;
 * @return {number}
 */
proto.SittelleProtos.Department.prototype.getMonObjectInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.setMonObjectInd = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated AdditionalParam additional_param_list = 8;
 * @return {!Array<!proto.SittelleProtos.AdditionalParam>}
 */
proto.SittelleProtos.Department.prototype.getAdditionalParamListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.AdditionalParam>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeTask_pb.AdditionalParam, 8));
};


/**
 * @param {!Array<!proto.SittelleProtos.AdditionalParam>} value
 * @return {!proto.SittelleProtos.Department} returns this
*/
proto.SittelleProtos.Department.prototype.setAdditionalParamListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.SittelleProtos.AdditionalParam=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.AdditionalParam}
 */
proto.SittelleProtos.Department.prototype.addAdditionalParamList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.SittelleProtos.AdditionalParam, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.Department} returns this
 */
proto.SittelleProtos.Department.prototype.clearAdditionalParamListList = function() {
  return this.setAdditionalParamListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.MonObjectSystem.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.MonObjectSystem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.MonObjectSystem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.MonObjectSystem.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    caption: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.MonObjectSystem}
 */
proto.SittelleProtos.MonObjectSystem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.MonObjectSystem;
  return proto.SittelleProtos.MonObjectSystem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.MonObjectSystem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.MonObjectSystem}
 */
proto.SittelleProtos.MonObjectSystem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.MonObjectSystem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.MonObjectSystem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.MonObjectSystem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.MonObjectSystem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.MonObjectSystem.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.MonObjectSystem} returns this
 */
proto.SittelleProtos.MonObjectSystem.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string caption = 2;
 * @return {string}
 */
proto.SittelleProtos.MonObjectSystem.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.MonObjectSystem} returns this
 */
proto.SittelleProtos.MonObjectSystem.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.Contract.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.Contract.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.Contract} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Contract.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    number: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dateAssign: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dateValdate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    dateClose: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.Contract}
 */
proto.SittelleProtos.Contract.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.Contract;
  return proto.SittelleProtos.Contract.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.Contract} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.Contract}
 */
proto.SittelleProtos.Contract.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateAssign(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateValdate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateClose(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.Contract.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.Contract.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.Contract} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Contract.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDateAssign();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDateValdate();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getDateClose();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.Contract.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Contract} returns this
 */
proto.SittelleProtos.Contract.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string number = 2;
 * @return {string}
 */
proto.SittelleProtos.Contract.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Contract} returns this
 */
proto.SittelleProtos.Contract.prototype.setNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 date_assign = 3;
 * @return {number}
 */
proto.SittelleProtos.Contract.prototype.getDateAssign = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Contract} returns this
 */
proto.SittelleProtos.Contract.prototype.setDateAssign = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 date_valdate = 4;
 * @return {number}
 */
proto.SittelleProtos.Contract.prototype.getDateValdate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Contract} returns this
 */
proto.SittelleProtos.Contract.prototype.setDateValdate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 date_close = 5;
 * @return {number}
 */
proto.SittelleProtos.Contract.prototype.getDateClose = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Contract} returns this
 */
proto.SittelleProtos.Contract.prototype.setDateClose = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ServiceOrganization.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ServiceOrganization.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ServiceOrganization.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ServiceOrganization} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ServiceOrganization.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    companyValue: (f = msg.getCompanyValue()) && proto.SittelleProtos.Company.toObject(includeInstance, f),
    contractValue: (f = msg.getContractValue()) && proto.SittelleProtos.Contract.toObject(includeInstance, f),
    monObjectSystem: (f = msg.getMonObjectSystem()) && proto.SittelleProtos.MonObjectSystem.toObject(includeInstance, f),
    employeeListList: jspb.Message.toObjectList(msg.getEmployeeListList(),
    proto.SittelleProtos.Employee.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ServiceOrganization}
 */
proto.SittelleProtos.ServiceOrganization.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ServiceOrganization;
  return proto.SittelleProtos.ServiceOrganization.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ServiceOrganization} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ServiceOrganization}
 */
proto.SittelleProtos.ServiceOrganization.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = new proto.SittelleProtos.Company;
      reader.readMessage(value,proto.SittelleProtos.Company.deserializeBinaryFromReader);
      msg.setCompanyValue(value);
      break;
    case 3:
      var value = new proto.SittelleProtos.Contract;
      reader.readMessage(value,proto.SittelleProtos.Contract.deserializeBinaryFromReader);
      msg.setContractValue(value);
      break;
    case 4:
      var value = new proto.SittelleProtos.MonObjectSystem;
      reader.readMessage(value,proto.SittelleProtos.MonObjectSystem.deserializeBinaryFromReader);
      msg.setMonObjectSystem(value);
      break;
    case 5:
      var value = new proto.SittelleProtos.Employee;
      reader.readMessage(value,proto.SittelleProtos.Employee.deserializeBinaryFromReader);
      msg.addEmployeeList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ServiceOrganization.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ServiceOrganization.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ServiceOrganization} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ServiceOrganization.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCompanyValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.SittelleProtos.Company.serializeBinaryToWriter
    );
  }
  f = message.getContractValue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.SittelleProtos.Contract.serializeBinaryToWriter
    );
  }
  f = message.getMonObjectSystem();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.SittelleProtos.MonObjectSystem.serializeBinaryToWriter
    );
  }
  f = message.getEmployeeListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.SittelleProtos.Employee.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ServiceOrganization.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
 */
proto.SittelleProtos.ServiceOrganization.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Company company_value = 2;
 * @return {?proto.SittelleProtos.Company}
 */
proto.SittelleProtos.ServiceOrganization.prototype.getCompanyValue = function() {
  return /** @type{?proto.SittelleProtos.Company} */ (
    jspb.Message.getWrapperField(this, proto.SittelleProtos.Company, 2));
};


/**
 * @param {?proto.SittelleProtos.Company|undefined} value
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
*/
proto.SittelleProtos.ServiceOrganization.prototype.setCompanyValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
 */
proto.SittelleProtos.ServiceOrganization.prototype.clearCompanyValue = function() {
  return this.setCompanyValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ServiceOrganization.prototype.hasCompanyValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Contract contract_value = 3;
 * @return {?proto.SittelleProtos.Contract}
 */
proto.SittelleProtos.ServiceOrganization.prototype.getContractValue = function() {
  return /** @type{?proto.SittelleProtos.Contract} */ (
    jspb.Message.getWrapperField(this, proto.SittelleProtos.Contract, 3));
};


/**
 * @param {?proto.SittelleProtos.Contract|undefined} value
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
*/
proto.SittelleProtos.ServiceOrganization.prototype.setContractValue = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
 */
proto.SittelleProtos.ServiceOrganization.prototype.clearContractValue = function() {
  return this.setContractValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ServiceOrganization.prototype.hasContractValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MonObjectSystem mon_object_system = 4;
 * @return {?proto.SittelleProtos.MonObjectSystem}
 */
proto.SittelleProtos.ServiceOrganization.prototype.getMonObjectSystem = function() {
  return /** @type{?proto.SittelleProtos.MonObjectSystem} */ (
    jspb.Message.getWrapperField(this, proto.SittelleProtos.MonObjectSystem, 4));
};


/**
 * @param {?proto.SittelleProtos.MonObjectSystem|undefined} value
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
*/
proto.SittelleProtos.ServiceOrganization.prototype.setMonObjectSystem = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
 */
proto.SittelleProtos.ServiceOrganization.prototype.clearMonObjectSystem = function() {
  return this.setMonObjectSystem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ServiceOrganization.prototype.hasMonObjectSystem = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Employee employee_list = 5;
 * @return {!Array<!proto.SittelleProtos.Employee>}
 */
proto.SittelleProtos.ServiceOrganization.prototype.getEmployeeListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.Employee>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.Employee, 5));
};


/**
 * @param {!Array<!proto.SittelleProtos.Employee>} value
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
*/
proto.SittelleProtos.ServiceOrganization.prototype.setEmployeeListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.SittelleProtos.Employee=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.Employee}
 */
proto.SittelleProtos.ServiceOrganization.prototype.addEmployeeList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.SittelleProtos.Employee, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ServiceOrganization} returns this
 */
proto.SittelleProtos.ServiceOrganization.prototype.clearEmployeeListList = function() {
  return this.setEmployeeListList([]);
};


goog.object.extend(exports, proto.SittelleProtos);
