// source: SittelleTypeNotification.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeTask_pb = require('./SittelleTypeTask_pb.js');
goog.object.extend(proto, SittelleTypeTask_pb);
var SittelleConst_pb = require('./SittelleConst_pb.js');
goog.object.extend(proto, SittelleConst_pb);
goog.exportSymbol('proto.SittelleProtos.Notification', null, global);
goog.exportSymbol('proto.SittelleProtos.NotifyFieldValue', null, global);
goog.exportSymbol('proto.SittelleProtos.TaskChangeNotification', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.NotifyFieldValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.NotifyFieldValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.NotifyFieldValue.displayName = 'proto.SittelleProtos.NotifyFieldValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.TaskChangeNotification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.TaskChangeNotification.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.TaskChangeNotification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.TaskChangeNotification.displayName = 'proto.SittelleProtos.TaskChangeNotification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.Notification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.Notification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.Notification.displayName = 'proto.SittelleProtos.Notification';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.NotifyFieldValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.NotifyFieldValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.NotifyFieldValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    valueCaption: jspb.Message.getFieldWithDefault(msg, 2, ""),
    valueData: msg.getValueData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.NotifyFieldValue}
 */
proto.SittelleProtos.NotifyFieldValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.NotifyFieldValue;
  return proto.SittelleProtos.NotifyFieldValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.NotifyFieldValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.NotifyFieldValue}
 */
proto.SittelleProtos.NotifyFieldValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValueCaption(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setValueData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.NotifyFieldValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.NotifyFieldValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.NotifyFieldValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getValueCaption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getValueData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional uint64 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.NotifyFieldValue} returns this
 */
proto.SittelleProtos.NotifyFieldValue.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string value_caption = 2;
 * @return {string}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.getValueCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.NotifyFieldValue} returns this
 */
proto.SittelleProtos.NotifyFieldValue.prototype.setValueCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes value_data = 3;
 * @return {!(string|Uint8Array)}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.getValueData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes value_data = 3;
 * This is a type-conversion wrapper around `getValueData()`
 * @return {string}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.getValueData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getValueData()));
};


/**
 * optional bytes value_data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getValueData()`
 * @return {!Uint8Array}
 */
proto.SittelleProtos.NotifyFieldValue.prototype.getValueData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getValueData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.SittelleProtos.NotifyFieldValue} returns this
 */
proto.SittelleProtos.NotifyFieldValue.prototype.setValueData = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.TaskChangeNotification.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.TaskChangeNotification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.TaskChangeNotification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.TaskChangeNotification.toObject = function(includeInstance, msg) {
  var f, obj = {
    actionType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sessInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    taskSett: (f = msg.getTaskSett()) && SittelleTypeTask_pb.TaskSett.toObject(includeInstance, f),
    accountApply: (f = msg.getAccountApply()) && SittelleTypeTask_pb.Account.toObject(includeInstance, f),
    applyDate: jspb.Message.getFieldWithDefault(msg, 5, 0),
    fieldValueListList: jspb.Message.toObjectList(msg.getFieldValueListList(),
    proto.SittelleProtos.NotifyFieldValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.TaskChangeNotification}
 */
proto.SittelleProtos.TaskChangeNotification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.TaskChangeNotification;
  return proto.SittelleProtos.TaskChangeNotification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.TaskChangeNotification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.TaskChangeNotification}
 */
proto.SittelleProtos.TaskChangeNotification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SittelleProtos.EnumTaskAction} */ (reader.readEnum());
      msg.setActionType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSessInd(value);
      break;
    case 3:
      var value = new SittelleTypeTask_pb.TaskSett;
      reader.readMessage(value,SittelleTypeTask_pb.TaskSett.deserializeBinaryFromReader);
      msg.setTaskSett(value);
      break;
    case 4:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.setAccountApply(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setApplyDate(value);
      break;
    case 6:
      var value = new proto.SittelleProtos.NotifyFieldValue;
      reader.readMessage(value,proto.SittelleProtos.NotifyFieldValue.deserializeBinaryFromReader);
      msg.addFieldValueList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.TaskChangeNotification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.TaskChangeNotification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.TaskChangeNotification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActionType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSessInd();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getTaskSett();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      SittelleTypeTask_pb.TaskSett.serializeBinaryToWriter
    );
  }
  f = message.getAccountApply();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getApplyDate();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getFieldValueListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.SittelleProtos.NotifyFieldValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional EnumTaskAction action_type = 1;
 * @return {!proto.SittelleProtos.EnumTaskAction}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getActionType = function() {
  return /** @type {!proto.SittelleProtos.EnumTaskAction} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.SittelleProtos.EnumTaskAction} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.setActionType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 sess_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getSessInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.setSessInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional TaskSett task_sett = 3;
 * @return {?proto.SittelleProtos.TaskSett}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getTaskSett = function() {
  return /** @type{?proto.SittelleProtos.TaskSett} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.TaskSett, 3));
};


/**
 * @param {?proto.SittelleProtos.TaskSett|undefined} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
*/
proto.SittelleProtos.TaskChangeNotification.prototype.setTaskSett = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.clearTaskSett = function() {
  return this.setTaskSett(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.hasTaskSett = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Account account_apply = 4;
 * @return {?proto.SittelleProtos.Account}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getAccountApply = function() {
  return /** @type{?proto.SittelleProtos.Account} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.Account, 4));
};


/**
 * @param {?proto.SittelleProtos.Account|undefined} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
*/
proto.SittelleProtos.TaskChangeNotification.prototype.setAccountApply = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.clearAccountApply = function() {
  return this.setAccountApply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.hasAccountApply = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 apply_date = 5;
 * @return {number}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getApplyDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.setApplyDate = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated NotifyFieldValue field_value_list = 6;
 * @return {!Array<!proto.SittelleProtos.NotifyFieldValue>}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.getFieldValueListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.NotifyFieldValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.NotifyFieldValue, 6));
};


/**
 * @param {!Array<!proto.SittelleProtos.NotifyFieldValue>} value
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
*/
proto.SittelleProtos.TaskChangeNotification.prototype.setFieldValueListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.SittelleProtos.NotifyFieldValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.NotifyFieldValue}
 */
proto.SittelleProtos.TaskChangeNotification.prototype.addFieldValueList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.SittelleProtos.NotifyFieldValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.TaskChangeNotification} returns this
 */
proto.SittelleProtos.TaskChangeNotification.prototype.clearFieldValueListList = function() {
  return this.setFieldValueListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.Notification.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.Notification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.Notification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Notification.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    object: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.Notification}
 */
proto.SittelleProtos.Notification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.Notification;
  return proto.SittelleProtos.Notification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.Notification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.Notification}
 */
proto.SittelleProtos.Notification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setObject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.Notification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.Notification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.Notification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.Notification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getObject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint32 type = 1;
 * @return {number}
 */
proto.SittelleProtos.Notification.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.Notification} returns this
 */
proto.SittelleProtos.Notification.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string object = 2;
 * @return {string}
 */
proto.SittelleProtos.Notification.prototype.getObject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.Notification} returns this
 */
proto.SittelleProtos.Notification.prototype.setObject = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.SittelleProtos);
