// source: SittelleTypeSystem.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeTask_pb = require('./SittelleTypeTask_pb.js');
goog.object.extend(proto, SittelleTypeTask_pb);
goog.exportSymbol('proto.SittelleProtos.DemmandItem', null, global);
goog.exportSymbol('proto.SittelleProtos.RoleDemandItem', null, global);
goog.exportSymbol('proto.SittelleProtos.RoleDemandType', null, global);
goog.exportSymbol('proto.SittelleProtos.RoleNotifyType', null, global);
goog.exportSymbol('proto.SittelleProtos.RoleRightType', null, global);
goog.exportSymbol('proto.SittelleProtos.SessionInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.RoleNotifyType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.RoleNotifyType.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.RoleNotifyType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.RoleNotifyType.displayName = 'proto.SittelleProtos.RoleNotifyType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.DemmandItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.DemmandItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.DemmandItem.displayName = 'proto.SittelleProtos.DemmandItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.RoleDemandItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.RoleDemandItem.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.RoleDemandItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.RoleDemandItem.displayName = 'proto.SittelleProtos.RoleDemandItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.RoleDemandType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.RoleDemandType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.RoleDemandType.displayName = 'proto.SittelleProtos.RoleDemandType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.RoleRightType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.RoleRightType.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.RoleRightType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.RoleRightType.displayName = 'proto.SittelleProtos.RoleRightType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.SessionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.SessionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.SessionInfo.displayName = 'proto.SittelleProtos.SessionInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.RoleNotifyType.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.RoleNotifyType.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.RoleNotifyType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.RoleNotifyType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleNotifyType.toObject = function(includeInstance, msg) {
  var f, obj = {
    rootTasktypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tasktypeInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    statusInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    taskroleInd: jspb.Message.getFieldWithDefault(msg, 4, 0),
    notify: jspb.Message.getFieldWithDefault(msg, 5, 0),
    accountListList: jspb.Message.toObjectList(msg.getAccountListList(),
    SittelleTypeTask_pb.Account.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.RoleNotifyType}
 */
proto.SittelleProtos.RoleNotifyType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.RoleNotifyType;
  return proto.SittelleProtos.RoleNotifyType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.RoleNotifyType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.RoleNotifyType}
 */
proto.SittelleProtos.RoleNotifyType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRootTasktypeInd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTasktypeInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatusInd(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskroleInd(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNotify(value);
      break;
    case 6:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.addAccountList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.RoleNotifyType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.RoleNotifyType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.RoleNotifyType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleNotifyType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRootTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getStatusInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTaskroleInd();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getNotify();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getAccountListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 root_tasktype_Ind = 1;
 * @return {number}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getRootTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.setRootTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 tasktype_Ind = 2;
 * @return {number}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.setTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 status_Ind = 3;
 * @return {number}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getStatusInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.setStatusInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 taskrole_Ind = 4;
 * @return {number}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getTaskroleInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.setTaskroleInd = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 notify = 5;
 * @return {number}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getNotify = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.setNotify = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated Account account_list = 6;
 * @return {!Array<!proto.SittelleProtos.Account>}
 */
proto.SittelleProtos.RoleNotifyType.prototype.getAccountListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.Account>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeTask_pb.Account, 6));
};


/**
 * @param {!Array<!proto.SittelleProtos.Account>} value
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
*/
proto.SittelleProtos.RoleNotifyType.prototype.setAccountListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.SittelleProtos.Account=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.Account}
 */
proto.SittelleProtos.RoleNotifyType.prototype.addAccountList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.SittelleProtos.Account, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.RoleNotifyType} returns this
 */
proto.SittelleProtos.RoleNotifyType.prototype.clearAccountListList = function() {
  return this.setAccountListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.DemmandItem.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.DemmandItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.DemmandItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.DemmandItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    rootTasktypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tasktypeInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    statusInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    demand: (f = msg.getDemand()) && SittelleTypeTask_pb.RoleDemand.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.DemmandItem}
 */
proto.SittelleProtos.DemmandItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.DemmandItem;
  return proto.SittelleProtos.DemmandItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.DemmandItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.DemmandItem}
 */
proto.SittelleProtos.DemmandItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRootTasktypeInd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTasktypeInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatusInd(value);
      break;
    case 4:
      var value = new SittelleTypeTask_pb.RoleDemand;
      reader.readMessage(value,SittelleTypeTask_pb.RoleDemand.deserializeBinaryFromReader);
      msg.setDemand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.DemmandItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.DemmandItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.DemmandItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.DemmandItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRootTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getStatusInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getDemand();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      SittelleTypeTask_pb.RoleDemand.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 root_taskType_Ind = 1;
 * @return {number}
 */
proto.SittelleProtos.DemmandItem.prototype.getRootTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.DemmandItem} returns this
 */
proto.SittelleProtos.DemmandItem.prototype.setRootTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 tasktype_Ind = 2;
 * @return {number}
 */
proto.SittelleProtos.DemmandItem.prototype.getTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.DemmandItem} returns this
 */
proto.SittelleProtos.DemmandItem.prototype.setTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 status_Ind = 3;
 * @return {number}
 */
proto.SittelleProtos.DemmandItem.prototype.getStatusInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.DemmandItem} returns this
 */
proto.SittelleProtos.DemmandItem.prototype.setStatusInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional RoleDemand demand = 4;
 * @return {?proto.SittelleProtos.RoleDemand}
 */
proto.SittelleProtos.DemmandItem.prototype.getDemand = function() {
  return /** @type{?proto.SittelleProtos.RoleDemand} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.RoleDemand, 4));
};


/**
 * @param {?proto.SittelleProtos.RoleDemand|undefined} value
 * @return {!proto.SittelleProtos.DemmandItem} returns this
*/
proto.SittelleProtos.DemmandItem.prototype.setDemand = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.DemmandItem} returns this
 */
proto.SittelleProtos.DemmandItem.prototype.clearDemand = function() {
  return this.setDemand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.DemmandItem.prototype.hasDemand = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.RoleDemandItem.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.RoleDemandItem.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.RoleDemandItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.RoleDemandItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleDemandItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    roleind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    demandListList: jspb.Message.toObjectList(msg.getDemandListList(),
    proto.SittelleProtos.DemmandItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.RoleDemandItem}
 */
proto.SittelleProtos.RoleDemandItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.RoleDemandItem;
  return proto.SittelleProtos.RoleDemandItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.RoleDemandItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.RoleDemandItem}
 */
proto.SittelleProtos.RoleDemandItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRoleind(value);
      break;
    case 2:
      var value = new proto.SittelleProtos.DemmandItem;
      reader.readMessage(value,proto.SittelleProtos.DemmandItem.deserializeBinaryFromReader);
      msg.addDemandList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.RoleDemandItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.RoleDemandItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.RoleDemandItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleDemandItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoleind();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getDemandListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SittelleProtos.DemmandItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 RoleInd = 1;
 * @return {number}
 */
proto.SittelleProtos.RoleDemandItem.prototype.getRoleind = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleDemandItem} returns this
 */
proto.SittelleProtos.RoleDemandItem.prototype.setRoleind = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated DemmandItem demand_list = 2;
 * @return {!Array<!proto.SittelleProtos.DemmandItem>}
 */
proto.SittelleProtos.RoleDemandItem.prototype.getDemandListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.DemmandItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.DemmandItem, 2));
};


/**
 * @param {!Array<!proto.SittelleProtos.DemmandItem>} value
 * @return {!proto.SittelleProtos.RoleDemandItem} returns this
*/
proto.SittelleProtos.RoleDemandItem.prototype.setDemandListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SittelleProtos.DemmandItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.DemmandItem}
 */
proto.SittelleProtos.RoleDemandItem.prototype.addDemandList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SittelleProtos.DemmandItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.RoleDemandItem} returns this
 */
proto.SittelleProtos.RoleDemandItem.prototype.clearDemandListList = function() {
  return this.setDemandListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.RoleDemandType.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.RoleDemandType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.RoleDemandType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleDemandType.toObject = function(includeInstance, msg) {
  var f, obj = {
    rootTasktypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tasktypeInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    statusInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    taskroleInd: jspb.Message.getFieldWithDefault(msg, 4, 0),
    demand: (f = msg.getDemand()) && SittelleTypeTask_pb.RoleDemand.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.RoleDemandType}
 */
proto.SittelleProtos.RoleDemandType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.RoleDemandType;
  return proto.SittelleProtos.RoleDemandType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.RoleDemandType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.RoleDemandType}
 */
proto.SittelleProtos.RoleDemandType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRootTasktypeInd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTasktypeInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatusInd(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskroleInd(value);
      break;
    case 5:
      var value = new SittelleTypeTask_pb.RoleDemand;
      reader.readMessage(value,SittelleTypeTask_pb.RoleDemand.deserializeBinaryFromReader);
      msg.setDemand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.RoleDemandType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.RoleDemandType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.RoleDemandType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleDemandType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRootTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getStatusInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTaskroleInd();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getDemand();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      SittelleTypeTask_pb.RoleDemand.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 root_tasktype_Ind = 1;
 * @return {number}
 */
proto.SittelleProtos.RoleDemandType.prototype.getRootTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
 */
proto.SittelleProtos.RoleDemandType.prototype.setRootTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 tasktype_Ind = 2;
 * @return {number}
 */
proto.SittelleProtos.RoleDemandType.prototype.getTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
 */
proto.SittelleProtos.RoleDemandType.prototype.setTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 status_Ind = 3;
 * @return {number}
 */
proto.SittelleProtos.RoleDemandType.prototype.getStatusInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
 */
proto.SittelleProtos.RoleDemandType.prototype.setStatusInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 taskrole_Ind = 4;
 * @return {number}
 */
proto.SittelleProtos.RoleDemandType.prototype.getTaskroleInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
 */
proto.SittelleProtos.RoleDemandType.prototype.setTaskroleInd = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional RoleDemand demand = 5;
 * @return {?proto.SittelleProtos.RoleDemand}
 */
proto.SittelleProtos.RoleDemandType.prototype.getDemand = function() {
  return /** @type{?proto.SittelleProtos.RoleDemand} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.RoleDemand, 5));
};


/**
 * @param {?proto.SittelleProtos.RoleDemand|undefined} value
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
*/
proto.SittelleProtos.RoleDemandType.prototype.setDemand = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.RoleDemandType} returns this
 */
proto.SittelleProtos.RoleDemandType.prototype.clearDemand = function() {
  return this.setDemand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.RoleDemandType.prototype.hasDemand = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.RoleRightType.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.RoleRightType.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.RoleRightType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.RoleRightType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleRightType.toObject = function(includeInstance, msg) {
  var f, obj = {
    rootTasktypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tasktypeInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    statusInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    taskroleInd: jspb.Message.getFieldWithDefault(msg, 4, 0),
    right: jspb.Message.getFieldWithDefault(msg, 5, 0),
    accountListList: jspb.Message.toObjectList(msg.getAccountListList(),
    SittelleTypeTask_pb.Account.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.RoleRightType}
 */
proto.SittelleProtos.RoleRightType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.RoleRightType;
  return proto.SittelleProtos.RoleRightType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.RoleRightType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.RoleRightType}
 */
proto.SittelleProtos.RoleRightType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRootTasktypeInd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTasktypeInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatusInd(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskroleInd(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRight(value);
      break;
    case 6:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.addAccountList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.RoleRightType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.RoleRightType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.RoleRightType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.RoleRightType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRootTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTasktypeInd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getStatusInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getTaskroleInd();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getRight();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getAccountListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 root_tasktype_Ind = 1;
 * @return {number}
 */
proto.SittelleProtos.RoleRightType.prototype.getRootTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.setRootTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 tasktype_Ind = 2;
 * @return {number}
 */
proto.SittelleProtos.RoleRightType.prototype.getTasktypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.setTasktypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 status_Ind = 3;
 * @return {number}
 */
proto.SittelleProtos.RoleRightType.prototype.getStatusInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.setStatusInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 taskrole_Ind = 4;
 * @return {number}
 */
proto.SittelleProtos.RoleRightType.prototype.getTaskroleInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.setTaskroleInd = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 right = 5;
 * @return {number}
 */
proto.SittelleProtos.RoleRightType.prototype.getRight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.setRight = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated Account account_list = 6;
 * @return {!Array<!proto.SittelleProtos.Account>}
 */
proto.SittelleProtos.RoleRightType.prototype.getAccountListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.Account>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeTask_pb.Account, 6));
};


/**
 * @param {!Array<!proto.SittelleProtos.Account>} value
 * @return {!proto.SittelleProtos.RoleRightType} returns this
*/
proto.SittelleProtos.RoleRightType.prototype.setAccountListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.SittelleProtos.Account=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.Account}
 */
proto.SittelleProtos.RoleRightType.prototype.addAccountList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.SittelleProtos.Account, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.RoleRightType} returns this
 */
proto.SittelleProtos.RoleRightType.prototype.clearAccountListList = function() {
  return this.setAccountListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.SessionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.SessionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.SessionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.SessionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    dateStart: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dateEnd: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ip: jspb.Message.getFieldWithDefault(msg, 5, ""),
    connectionContext: jspb.Message.getFieldWithDefault(msg, 6, ""),
    account: (f = msg.getAccount()) && SittelleTypeTask_pb.Account.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.SessionInfo}
 */
proto.SittelleProtos.SessionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.SessionInfo;
  return proto.SittelleProtos.SessionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.SessionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.SessionInfo}
 */
proto.SittelleProtos.SessionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateStart(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateEnd(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionContext(value);
      break;
    case 7:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.SessionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.SessionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.SessionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.SessionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDateStart();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDateEnd();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getConnectionContext();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.SessionInfo.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.SittelleProtos.SessionInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 date_start = 3;
 * @return {number}
 */
proto.SittelleProtos.SessionInfo.prototype.getDateStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setDateStart = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 date_end = 4;
 * @return {number}
 */
proto.SittelleProtos.SessionInfo.prototype.getDateEnd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setDateEnd = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string ip = 5;
 * @return {string}
 */
proto.SittelleProtos.SessionInfo.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setIp = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string connection_context = 6;
 * @return {string}
 */
proto.SittelleProtos.SessionInfo.prototype.getConnectionContext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.setConnectionContext = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Account account = 7;
 * @return {?proto.SittelleProtos.Account}
 */
proto.SittelleProtos.SessionInfo.prototype.getAccount = function() {
  return /** @type{?proto.SittelleProtos.Account} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.Account, 7));
};


/**
 * @param {?proto.SittelleProtos.Account|undefined} value
 * @return {!proto.SittelleProtos.SessionInfo} returns this
*/
proto.SittelleProtos.SessionInfo.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.SessionInfo} returns this
 */
proto.SittelleProtos.SessionInfo.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.SessionInfo.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.SittelleProtos);
