// source: SittelleServiceReport.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeReport_pb = require('./SittelleTypeReport_pb.js');
goog.object.extend(proto, SittelleTypeReport_pb);
var SittelleTypeManual_pb = require('./SittelleTypeManual_pb.js');
goog.object.extend(proto, SittelleTypeManual_pb);
var SittelleTypeDictionary_pb = require('./SittelleTypeDictionary_pb.js');
goog.object.extend(proto, SittelleTypeDictionary_pb);
goog.exportSymbol('proto.SittelleProtos.GeneratedReportRequest', null, global);
goog.exportSymbol('proto.SittelleProtos.GeneratedReportRes', null, global);
goog.exportSymbol('proto.SittelleProtos.ReportListRequest', null, global);
goog.exportSymbol('proto.SittelleProtos.ReportListRes', null, global);
goog.exportSymbol('proto.SittelleProtos.ReportParamsRequest', null, global);
goog.exportSymbol('proto.SittelleProtos.ReportParamsRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ReportListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ReportListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ReportListRequest.displayName = 'proto.SittelleProtos.ReportListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ReportListRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ReportListRes.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ReportListRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ReportListRes.displayName = 'proto.SittelleProtos.ReportListRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ReportParamsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ReportParamsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ReportParamsRequest.displayName = 'proto.SittelleProtos.ReportParamsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ReportParamsRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ReportParamsRes.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ReportParamsRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ReportParamsRes.displayName = 'proto.SittelleProtos.ReportParamsRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.GeneratedReportRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.GeneratedReportRequest.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.GeneratedReportRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.GeneratedReportRequest.displayName = 'proto.SittelleProtos.GeneratedReportRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.GeneratedReportRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.GeneratedReportRes.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.GeneratedReportRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.GeneratedReportRes.displayName = 'proto.SittelleProtos.GeneratedReportRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ReportListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ReportListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ReportListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectionInd: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ReportListRequest}
 */
proto.SittelleProtos.ReportListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ReportListRequest;
  return proto.SittelleProtos.ReportListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ReportListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ReportListRequest}
 */
proto.SittelleProtos.ReportListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnectionInd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ReportListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ReportListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ReportListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectionInd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string sess_id = 1;
 * @return {string}
 */
proto.SittelleProtos.ReportListRequest.prototype.getSessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ReportListRequest} returns this
 */
proto.SittelleProtos.ReportListRequest.prototype.setSessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 connection_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.ReportListRequest.prototype.getConnectionInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ReportListRequest} returns this
 */
proto.SittelleProtos.ReportListRequest.prototype.setConnectionInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ReportListRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ReportListRes.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ReportListRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ReportListRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportListRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    listList: jspb.Message.toObjectList(msg.getListList(),
    SittelleTypeReport_pb.ReportSett.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ReportListRes}
 */
proto.SittelleProtos.ReportListRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ReportListRes;
  return proto.SittelleProtos.ReportListRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ReportListRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ReportListRes}
 */
proto.SittelleProtos.ReportListRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SittelleTypeReport_pb.ReportSett;
      reader.readMessage(value,SittelleTypeReport_pb.ReportSett.deserializeBinaryFromReader);
      msg.addList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ReportListRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ReportListRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ReportListRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportListRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      SittelleTypeReport_pb.ReportSett.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ReportSett list = 1;
 * @return {!Array<!proto.SittelleProtos.ReportSett>}
 */
proto.SittelleProtos.ReportListRes.prototype.getListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ReportSett>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeReport_pb.ReportSett, 1));
};


/**
 * @param {!Array<!proto.SittelleProtos.ReportSett>} value
 * @return {!proto.SittelleProtos.ReportListRes} returns this
*/
proto.SittelleProtos.ReportListRes.prototype.setListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SittelleProtos.ReportSett=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ReportSett}
 */
proto.SittelleProtos.ReportListRes.prototype.addList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SittelleProtos.ReportSett, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ReportListRes} returns this
 */
proto.SittelleProtos.ReportListRes.prototype.clearListList = function() {
  return this.setListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ReportParamsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ReportParamsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ReportParamsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportParamsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectionInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    reportInd: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ReportParamsRequest}
 */
proto.SittelleProtos.ReportParamsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ReportParamsRequest;
  return proto.SittelleProtos.ReportParamsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ReportParamsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ReportParamsRequest}
 */
proto.SittelleProtos.ReportParamsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnectionInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReportInd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ReportParamsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ReportParamsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ReportParamsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportParamsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectionInd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReportInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional string sess_id = 1;
 * @return {string}
 */
proto.SittelleProtos.ReportParamsRequest.prototype.getSessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ReportParamsRequest} returns this
 */
proto.SittelleProtos.ReportParamsRequest.prototype.setSessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 connection_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.ReportParamsRequest.prototype.getConnectionInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ReportParamsRequest} returns this
 */
proto.SittelleProtos.ReportParamsRequest.prototype.setConnectionInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 report_ind = 3;
 * @return {number}
 */
proto.SittelleProtos.ReportParamsRequest.prototype.getReportInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ReportParamsRequest} returns this
 */
proto.SittelleProtos.ReportParamsRequest.prototype.setReportInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ReportParamsRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ReportParamsRes.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ReportParamsRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ReportParamsRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportParamsRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestListList: jspb.Message.toObjectList(msg.getRequestListList(),
    SittelleTypeManual_pb.ManualRequestValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ReportParamsRes}
 */
proto.SittelleProtos.ReportParamsRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ReportParamsRes;
  return proto.SittelleProtos.ReportParamsRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ReportParamsRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ReportParamsRes}
 */
proto.SittelleProtos.ReportParamsRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SittelleTypeManual_pb.ManualRequestValue;
      reader.readMessage(value,SittelleTypeManual_pb.ManualRequestValue.deserializeBinaryFromReader);
      msg.addRequestList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ReportParamsRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ReportParamsRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ReportParamsRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ReportParamsRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      SittelleTypeManual_pb.ManualRequestValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ManualRequestValue request_list = 1;
 * @return {!Array<!proto.SittelleProtos.ManualRequestValue>}
 */
proto.SittelleProtos.ReportParamsRes.prototype.getRequestListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualRequestValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeManual_pb.ManualRequestValue, 1));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualRequestValue>} value
 * @return {!proto.SittelleProtos.ReportParamsRes} returns this
*/
proto.SittelleProtos.ReportParamsRes.prototype.setRequestListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SittelleProtos.ManualRequestValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualRequestValue}
 */
proto.SittelleProtos.ReportParamsRes.prototype.addRequestList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SittelleProtos.ManualRequestValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ReportParamsRes} returns this
 */
proto.SittelleProtos.ReportParamsRes.prototype.clearRequestListList = function() {
  return this.setRequestListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.GeneratedReportRequest.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.GeneratedReportRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.GeneratedReportRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.GeneratedReportRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectionInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    reportInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    paramListList: jspb.Message.toObjectList(msg.getParamListList(),
    SittelleTypeManual_pb.ManualValue.toObject, includeInstance),
    generateTimeout: jspb.Message.getFieldWithDefault(msg, 5, 0),
    generateRecordCouet: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.GeneratedReportRequest}
 */
proto.SittelleProtos.GeneratedReportRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.GeneratedReportRequest;
  return proto.SittelleProtos.GeneratedReportRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.GeneratedReportRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.GeneratedReportRequest}
 */
proto.SittelleProtos.GeneratedReportRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnectionInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReportInd(value);
      break;
    case 4:
      var value = new SittelleTypeManual_pb.ManualValue;
      reader.readMessage(value,SittelleTypeManual_pb.ManualValue.deserializeBinaryFromReader);
      msg.addParamList(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGenerateTimeout(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setGenerateRecordCouet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.GeneratedReportRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.GeneratedReportRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.GeneratedReportRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectionInd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReportInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getParamListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      SittelleTypeManual_pb.ManualValue.serializeBinaryToWriter
    );
  }
  f = message.getGenerateTimeout();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getGenerateRecordCouet();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
};


/**
 * optional string sess_id = 1;
 * @return {string}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getSessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.setSessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 connection_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getConnectionInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.setConnectionInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 report_ind = 3;
 * @return {number}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getReportInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.setReportInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated ManualValue param_list = 4;
 * @return {!Array<!proto.SittelleProtos.ManualValue>}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getParamListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeManual_pb.ManualValue, 4));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualValue>} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
*/
proto.SittelleProtos.GeneratedReportRequest.prototype.setParamListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.SittelleProtos.ManualValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualValue}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.addParamList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.SittelleProtos.ManualValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.clearParamListList = function() {
  return this.setParamListList([]);
};


/**
 * optional uint64 generate_timeout = 5;
 * @return {number}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getGenerateTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.setGenerateTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 generate_record_couet = 6;
 * @return {number}
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.getGenerateRecordCouet = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.GeneratedReportRequest} returns this
 */
proto.SittelleProtos.GeneratedReportRequest.prototype.setGenerateRecordCouet = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.GeneratedReportRes.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.GeneratedReportRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.GeneratedReportRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.GeneratedReportRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    headerListList: jspb.Message.toObjectList(msg.getHeaderListList(),
    SittelleTypeReport_pb.ReportHeader.toObject, includeInstance),
    valueListList: jspb.Message.toObjectList(msg.getValueListList(),
    SittelleTypeReport_pb.ReportValue.toObject, includeInstance),
    headerChartList: jspb.Message.toObjectList(msg.getHeaderChartList(),
    SittelleTypeReport_pb.ReportHeaderGroup.toObject, includeInstance),
    chartListList: jspb.Message.toObjectList(msg.getChartListList(),
    SittelleTypeDictionary_pb.SittelleChart.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.GeneratedReportRes}
 */
proto.SittelleProtos.GeneratedReportRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.GeneratedReportRes;
  return proto.SittelleProtos.GeneratedReportRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.GeneratedReportRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.GeneratedReportRes}
 */
proto.SittelleProtos.GeneratedReportRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SittelleTypeReport_pb.ReportHeader;
      reader.readMessage(value,SittelleTypeReport_pb.ReportHeader.deserializeBinaryFromReader);
      msg.addHeaderList(value);
      break;
    case 2:
      var value = new SittelleTypeReport_pb.ReportValue;
      reader.readMessage(value,SittelleTypeReport_pb.ReportValue.deserializeBinaryFromReader);
      msg.addValueList(value);
      break;
    case 3:
      var value = new SittelleTypeReport_pb.ReportHeaderGroup;
      reader.readMessage(value,SittelleTypeReport_pb.ReportHeaderGroup.deserializeBinaryFromReader);
      msg.addHeaderChart(value);
      break;
    case 4:
      var value = new SittelleTypeDictionary_pb.SittelleChart;
      reader.readMessage(value,SittelleTypeDictionary_pb.SittelleChart.deserializeBinaryFromReader);
      msg.addChartList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.GeneratedReportRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.GeneratedReportRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.GeneratedReportRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaderListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      SittelleTypeReport_pb.ReportHeader.serializeBinaryToWriter
    );
  }
  f = message.getValueListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      SittelleTypeReport_pb.ReportValue.serializeBinaryToWriter
    );
  }
  f = message.getHeaderChartList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      SittelleTypeReport_pb.ReportHeaderGroup.serializeBinaryToWriter
    );
  }
  f = message.getChartListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      SittelleTypeDictionary_pb.SittelleChart.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ReportHeader header_list = 1;
 * @return {!Array<!proto.SittelleProtos.ReportHeader>}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.getHeaderListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ReportHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeReport_pb.ReportHeader, 1));
};


/**
 * @param {!Array<!proto.SittelleProtos.ReportHeader>} value
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
*/
proto.SittelleProtos.GeneratedReportRes.prototype.setHeaderListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.SittelleProtos.ReportHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ReportHeader}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.addHeaderList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.SittelleProtos.ReportHeader, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
 */
proto.SittelleProtos.GeneratedReportRes.prototype.clearHeaderListList = function() {
  return this.setHeaderListList([]);
};


/**
 * repeated ReportValue value_list = 2;
 * @return {!Array<!proto.SittelleProtos.ReportValue>}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.getValueListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ReportValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeReport_pb.ReportValue, 2));
};


/**
 * @param {!Array<!proto.SittelleProtos.ReportValue>} value
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
*/
proto.SittelleProtos.GeneratedReportRes.prototype.setValueListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SittelleProtos.ReportValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ReportValue}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.addValueList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SittelleProtos.ReportValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
 */
proto.SittelleProtos.GeneratedReportRes.prototype.clearValueListList = function() {
  return this.setValueListList([]);
};


/**
 * repeated ReportHeaderGroup header_chart = 3;
 * @return {!Array<!proto.SittelleProtos.ReportHeaderGroup>}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.getHeaderChartList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ReportHeaderGroup>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeReport_pb.ReportHeaderGroup, 3));
};


/**
 * @param {!Array<!proto.SittelleProtos.ReportHeaderGroup>} value
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
*/
proto.SittelleProtos.GeneratedReportRes.prototype.setHeaderChartList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.SittelleProtos.ReportHeaderGroup=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ReportHeaderGroup}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.addHeaderChart = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.SittelleProtos.ReportHeaderGroup, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
 */
proto.SittelleProtos.GeneratedReportRes.prototype.clearHeaderChartList = function() {
  return this.setHeaderChartList([]);
};


/**
 * repeated SittelleChart chart_list = 4;
 * @return {!Array<!proto.SittelleProtos.SittelleChart>}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.getChartListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.SittelleChart>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeDictionary_pb.SittelleChart, 4));
};


/**
 * @param {!Array<!proto.SittelleProtos.SittelleChart>} value
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
*/
proto.SittelleProtos.GeneratedReportRes.prototype.setChartListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.SittelleProtos.SittelleChart=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.SittelleChart}
 */
proto.SittelleProtos.GeneratedReportRes.prototype.addChartList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.SittelleProtos.SittelleChart, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.GeneratedReportRes} returns this
 */
proto.SittelleProtos.GeneratedReportRes.prototype.clearChartListList = function() {
  return this.setChartListList([]);
};


goog.object.extend(exports, proto.SittelleProtos);
