// source: SittelleServiceAuthorization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeTask_pb = require('./SittelleTypeTask_pb.js');
goog.object.extend(proto, SittelleTypeTask_pb);
goog.exportSymbol('proto.SittelleProtos.ConnectionRightsRequest', null, global);
goog.exportSymbol('proto.SittelleProtos.ConnectionRightsRes', null, global);
goog.exportSymbol('proto.SittelleProtos.ExternalConnectionCloseByAccountRequest', null, global);
goog.exportSymbol('proto.SittelleProtos.ExternalConnectionCloseByAccountRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ConnectionRightsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ConnectionRightsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ConnectionRightsRequest.displayName = 'proto.SittelleProtos.ConnectionRightsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ConnectionRightsRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ConnectionRightsRes.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ConnectionRightsRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ConnectionRightsRes.displayName = 'proto.SittelleProtos.ConnectionRightsRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ExternalConnectionCloseByAccountRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.displayName = 'proto.SittelleProtos.ExternalConnectionCloseByAccountRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ExternalConnectionCloseByAccountRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ExternalConnectionCloseByAccountRes.displayName = 'proto.SittelleProtos.ExternalConnectionCloseByAccountRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ConnectionRightsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ConnectionRightsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ConnectionRightsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectionInd: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ConnectionRightsRequest}
 */
proto.SittelleProtos.ConnectionRightsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ConnectionRightsRequest;
  return proto.SittelleProtos.ConnectionRightsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ConnectionRightsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ConnectionRightsRequest}
 */
proto.SittelleProtos.ConnectionRightsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnectionInd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ConnectionRightsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ConnectionRightsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ConnectionRightsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectionInd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string sess_id = 1;
 * @return {string}
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.getSessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ConnectionRightsRequest} returns this
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.setSessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 connection_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.getConnectionInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ConnectionRightsRequest} returns this
 */
proto.SittelleProtos.ConnectionRightsRequest.prototype.setConnectionInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ConnectionRightsRes.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ConnectionRightsRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ConnectionRightsRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ConnectionRightsRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    account: (f = msg.getAccount()) && SittelleTypeTask_pb.Account.toObject(includeInstance, f),
    taskRights: jspb.Message.getFieldWithDefault(msg, 2, 0),
    configRights: jspb.Message.getFieldWithDefault(msg, 3, 0),
    accountGroupListList: jspb.Message.toObjectList(msg.getAccountGroupListList(),
    SittelleTypeTask_pb.AccountGroup.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ConnectionRightsRes}
 */
proto.SittelleProtos.ConnectionRightsRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ConnectionRightsRes;
  return proto.SittelleProtos.ConnectionRightsRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ConnectionRightsRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ConnectionRightsRes}
 */
proto.SittelleProtos.ConnectionRightsRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTaskRights(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setConfigRights(value);
      break;
    case 4:
      var value = new SittelleTypeTask_pb.AccountGroup;
      reader.readMessage(value,SittelleTypeTask_pb.AccountGroup.deserializeBinaryFromReader);
      msg.addAccountGroupList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ConnectionRightsRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ConnectionRightsRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ConnectionRightsRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getTaskRights();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getConfigRights();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getAccountGroupListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      SittelleTypeTask_pb.AccountGroup.serializeBinaryToWriter
    );
  }
};


/**
 * optional Account account = 1;
 * @return {?proto.SittelleProtos.Account}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.getAccount = function() {
  return /** @type{?proto.SittelleProtos.Account} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.Account, 1));
};


/**
 * @param {?proto.SittelleProtos.Account|undefined} value
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
*/
proto.SittelleProtos.ConnectionRightsRes.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 task_rights = 2;
 * @return {number}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.getTaskRights = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.setTaskRights = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 config_rights = 3;
 * @return {number}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.getConfigRights = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.setConfigRights = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated AccountGroup account_group_list = 4;
 * @return {!Array<!proto.SittelleProtos.AccountGroup>}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.getAccountGroupListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.AccountGroup>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeTask_pb.AccountGroup, 4));
};


/**
 * @param {!Array<!proto.SittelleProtos.AccountGroup>} value
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
*/
proto.SittelleProtos.ConnectionRightsRes.prototype.setAccountGroupListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.SittelleProtos.AccountGroup=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.AccountGroup}
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.addAccountGroupList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.SittelleProtos.AccountGroup, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ConnectionRightsRes} returns this
 */
proto.SittelleProtos.ConnectionRightsRes.prototype.clearAccountGroupListList = function() {
  return this.setAccountGroupListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    connectionInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    accountInd: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ExternalConnectionCloseByAccountRequest;
  return proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnectionInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccountInd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConnectionInd();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAccountInd();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional string sess_id = 1;
 * @return {string}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.getSessId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} returns this
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.setSessId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 connection_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.getConnectionInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} returns this
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.setConnectionInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 account_ind = 3;
 * @return {number}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.getAccountInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRequest} returns this
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRequest.prototype.setAccountInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ExternalConnectionCloseByAccountRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRes}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ExternalConnectionCloseByAccountRes;
  return proto.SittelleProtos.ExternalConnectionCloseByAccountRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ExternalConnectionCloseByAccountRes}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ExternalConnectionCloseByAccountRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ExternalConnectionCloseByAccountRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalConnectionCloseByAccountRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.SittelleProtos);
