// source: SittelleTypeClient.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var SittelleTypeTask_pb = require('./SittelleTypeTask_pb.js');
goog.object.extend(proto, SittelleTypeTask_pb);
var SittelleTypeManual_pb = require('./SittelleTypeManual_pb.js');
goog.object.extend(proto, SittelleTypeManual_pb);
goog.exportSymbol('proto.SittelleProtos.ExternalInputSett', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualValueCardInfo', null, global);
goog.exportSymbol('proto.SittelleProtos.TaskHistoryItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ExternalInputSett = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ExternalInputSett.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ExternalInputSett, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ExternalInputSett.displayName = 'proto.SittelleProtos.ExternalInputSett';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualValueCardInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ManualValueCardInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualValueCardInfo.displayName = 'proto.SittelleProtos.ManualValueCardInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.TaskHistoryItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.TaskHistoryItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.TaskHistoryItem.displayName = 'proto.SittelleProtos.TaskHistoryItem';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ExternalInputSett.repeatedFields_ = [7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ExternalInputSett.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ExternalInputSett.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ExternalInputSett} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalInputSett.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    subtaskPathInd: jspb.Message.getFieldWithDefault(msg, 2, 0),
    fieldManual: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fieldAuto: jspb.Message.getFieldWithDefault(msg, 4, 0),
    statusInd: jspb.Message.getFieldWithDefault(msg, 5, 0),
    valueList: (f = msg.getValueList()) && SittelleTypeTask_pb.TaskFieldsInputValues.toObject(includeInstance, f),
    manualRequestList: jspb.Message.toObjectList(msg.getManualRequestList(),
    SittelleTypeManual_pb.ManualRequestValue.toObject, includeInstance),
    roleRequestList: jspb.Message.toObjectList(msg.getRoleRequestList(),
    SittelleTypeTask_pb.TaskRole.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ExternalInputSett}
 */
proto.SittelleProtos.ExternalInputSett.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ExternalInputSett;
  return proto.SittelleProtos.ExternalInputSett.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ExternalInputSett} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ExternalInputSett}
 */
proto.SittelleProtos.ExternalInputSett.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSubtaskPathInd(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFieldManual(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFieldAuto(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStatusInd(value);
      break;
    case 6:
      var value = new SittelleTypeTask_pb.TaskFieldsInputValues;
      reader.readMessage(value,SittelleTypeTask_pb.TaskFieldsInputValues.deserializeBinaryFromReader);
      msg.setValueList(value);
      break;
    case 7:
      var value = new SittelleTypeManual_pb.ManualRequestValue;
      reader.readMessage(value,SittelleTypeManual_pb.ManualRequestValue.deserializeBinaryFromReader);
      msg.addManualRequest(value);
      break;
    case 8:
      var value = new SittelleTypeTask_pb.TaskRole;
      reader.readMessage(value,SittelleTypeTask_pb.TaskRole.deserializeBinaryFromReader);
      msg.addRoleRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ExternalInputSett.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ExternalInputSett.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ExternalInputSett} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ExternalInputSett.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getSubtaskPathInd();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getFieldManual();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getFieldAuto();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getStatusInd();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getValueList();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      SittelleTypeTask_pb.TaskFieldsInputValues.serializeBinaryToWriter
    );
  }
  f = message.getManualRequestList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      SittelleTypeManual_pb.ManualRequestValue.serializeBinaryToWriter
    );
  }
  f = message.getRoleRequestList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      SittelleTypeTask_pb.TaskRole.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 subtask_path_ind = 2;
 * @return {number}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getSubtaskPathInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.setSubtaskPathInd = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 field_manual = 3;
 * @return {number}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getFieldManual = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.setFieldManual = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 field_auto = 4;
 * @return {number}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getFieldAuto = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.setFieldAuto = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 status_ind = 5;
 * @return {number}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getStatusInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.setStatusInd = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional TaskFieldsInputValues value_list = 6;
 * @return {?proto.SittelleProtos.TaskFieldsInputValues}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getValueList = function() {
  return /** @type{?proto.SittelleProtos.TaskFieldsInputValues} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.TaskFieldsInputValues, 6));
};


/**
 * @param {?proto.SittelleProtos.TaskFieldsInputValues|undefined} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
*/
proto.SittelleProtos.ExternalInputSett.prototype.setValueList = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.clearValueList = function() {
  return this.setValueList(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ExternalInputSett.prototype.hasValueList = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated ManualRequestValue manual_request = 7;
 * @return {!Array<!proto.SittelleProtos.ManualRequestValue>}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getManualRequestList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualRequestValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeManual_pb.ManualRequestValue, 7));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualRequestValue>} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
*/
proto.SittelleProtos.ExternalInputSett.prototype.setManualRequestList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.SittelleProtos.ManualRequestValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualRequestValue}
 */
proto.SittelleProtos.ExternalInputSett.prototype.addManualRequest = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.SittelleProtos.ManualRequestValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.clearManualRequestList = function() {
  return this.setManualRequestList([]);
};


/**
 * repeated TaskRole role_request = 8;
 * @return {!Array<!proto.SittelleProtos.TaskRole>}
 */
proto.SittelleProtos.ExternalInputSett.prototype.getRoleRequestList = function() {
  return /** @type{!Array<!proto.SittelleProtos.TaskRole>} */ (
    jspb.Message.getRepeatedWrapperField(this, SittelleTypeTask_pb.TaskRole, 8));
};


/**
 * @param {!Array<!proto.SittelleProtos.TaskRole>} value
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
*/
proto.SittelleProtos.ExternalInputSett.prototype.setRoleRequestList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.SittelleProtos.TaskRole=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.TaskRole}
 */
proto.SittelleProtos.ExternalInputSett.prototype.addRoleRequest = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.SittelleProtos.TaskRole, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ExternalInputSett} returns this
 */
proto.SittelleProtos.ExternalInputSett.prototype.clearRoleRequestList = function() {
  return this.setRoleRequestList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualValueCardInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualValueCardInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualValueCardInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    manualValue: (f = msg.getManualValue()) && SittelleTypeManual_pb.ManualValue.toObject(includeInstance, f),
    paramCaption: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualValueCardInfo}
 */
proto.SittelleProtos.ManualValueCardInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualValueCardInfo;
  return proto.SittelleProtos.ManualValueCardInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualValueCardInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualValueCardInfo}
 */
proto.SittelleProtos.ManualValueCardInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new SittelleTypeManual_pb.ManualValue;
      reader.readMessage(value,SittelleTypeManual_pb.ManualValue.deserializeBinaryFromReader);
      msg.setManualValue(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setParamCaption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualValueCardInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualValueCardInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualValueCardInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getManualValue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      SittelleTypeManual_pb.ManualValue.serializeBinaryToWriter
    );
  }
  f = message.getParamCaption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ManualValue manual_value = 1;
 * @return {?proto.SittelleProtos.ManualValue}
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.getManualValue = function() {
  return /** @type{?proto.SittelleProtos.ManualValue} */ (
    jspb.Message.getWrapperField(this, SittelleTypeManual_pb.ManualValue, 1));
};


/**
 * @param {?proto.SittelleProtos.ManualValue|undefined} value
 * @return {!proto.SittelleProtos.ManualValueCardInfo} returns this
*/
proto.SittelleProtos.ManualValueCardInfo.prototype.setManualValue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ManualValueCardInfo} returns this
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.clearManualValue = function() {
  return this.setManualValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.hasManualValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string param_caption = 2;
 * @return {string}
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.getParamCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualValueCardInfo} returns this
 */
proto.SittelleProtos.ManualValueCardInfo.prototype.setParamCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.TaskHistoryItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.TaskHistoryItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.TaskHistoryItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    dateApply: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accountApply: (f = msg.getAccountApply()) && SittelleTypeTask_pb.Account.toObject(includeInstance, f),
    sessInd: jspb.Message.getFieldWithDefault(msg, 3, 0),
    action: jspb.Message.getFieldWithDefault(msg, 4, 0),
    field: jspb.Message.getFieldWithDefault(msg, 5, 0),
    applyData: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.TaskHistoryItem}
 */
proto.SittelleProtos.TaskHistoryItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.TaskHistoryItem;
  return proto.SittelleProtos.TaskHistoryItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.TaskHistoryItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.TaskHistoryItem}
 */
proto.SittelleProtos.TaskHistoryItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDateApply(value);
      break;
    case 2:
      var value = new SittelleTypeTask_pb.Account;
      reader.readMessage(value,SittelleTypeTask_pb.Account.deserializeBinaryFromReader);
      msg.setAccountApply(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSessInd(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAction(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setField(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplyData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.TaskHistoryItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.TaskHistoryItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.TaskHistoryItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDateApply();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAccountApply();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      SittelleTypeTask_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getSessInd();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getAction();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getField();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getApplyData();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int64 date_apply = 1;
 * @return {number}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getDateApply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.setDateApply = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Account account_apply = 2;
 * @return {?proto.SittelleProtos.Account}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getAccountApply = function() {
  return /** @type{?proto.SittelleProtos.Account} */ (
    jspb.Message.getWrapperField(this, SittelleTypeTask_pb.Account, 2));
};


/**
 * @param {?proto.SittelleProtos.Account|undefined} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
*/
proto.SittelleProtos.TaskHistoryItem.prototype.setAccountApply = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.clearAccountApply = function() {
  return this.setAccountApply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.hasAccountApply = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint64 sess_ind = 3;
 * @return {number}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getSessInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.setSessInd = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 action = 4;
 * @return {number}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getAction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.setAction = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 field = 5;
 * @return {number}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getField = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.setField = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string apply_data = 6;
 * @return {string}
 */
proto.SittelleProtos.TaskHistoryItem.prototype.getApplyData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.TaskHistoryItem} returns this
 */
proto.SittelleProtos.TaskHistoryItem.prototype.setApplyData = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.SittelleProtos);
