// source: SittelleTypeManual.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.SittelleProtos.ManualDependentValue', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualListValue', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualParam', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualQuery', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualQueryApplyTaskType', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualRequestValue', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualTaskType', null, global);
goog.exportSymbol('proto.SittelleProtos.ManualValue', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ManualValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualValue.displayName = 'proto.SittelleProtos.ManualValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualListValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ManualListValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualListValue.displayName = 'proto.SittelleProtos.ManualListValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualDependentValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ManualDependentValue.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ManualDependentValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualDependentValue.displayName = 'proto.SittelleProtos.ManualDependentValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualRequestValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ManualRequestValue.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ManualRequestValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualRequestValue.displayName = 'proto.SittelleProtos.ManualRequestValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SittelleProtos.ManualQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualQuery.displayName = 'proto.SittelleProtos.ManualQuery';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualParam = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ManualParam.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ManualParam, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualParam.displayName = 'proto.SittelleProtos.ManualParam';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualTaskType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ManualTaskType.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ManualTaskType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualTaskType.displayName = 'proto.SittelleProtos.ManualTaskType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SittelleProtos.ManualQueryApplyTaskType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SittelleProtos.ManualQueryApplyTaskType.repeatedFields_, null);
};
goog.inherits(proto.SittelleProtos.ManualQueryApplyTaskType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SittelleProtos.ManualQueryApplyTaskType.displayName = 'proto.SittelleProtos.ManualQueryApplyTaskType';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualValue.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    paramInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFieldWithDefault(msg, 2, ""),
    caption: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualValue}
 */
proto.SittelleProtos.ManualValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualValue;
  return proto.SittelleProtos.ManualValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualValue}
 */
proto.SittelleProtos.ManualValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setParamInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParamInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional uint32 param_ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ManualValue.prototype.getParamInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualValue} returns this
 */
proto.SittelleProtos.ManualValue.prototype.setParamInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.SittelleProtos.ManualValue.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualValue} returns this
 */
proto.SittelleProtos.ManualValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string caption = 3;
 * @return {string}
 */
proto.SittelleProtos.ManualValue.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualValue} returns this
 */
proto.SittelleProtos.ManualValue.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualListValue.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualListValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualListValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualListValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, ""),
    caption: jspb.Message.getFieldWithDefault(msg, 2, ""),
    descr: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualListValue}
 */
proto.SittelleProtos.ManualListValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualListValue;
  return proto.SittelleProtos.ManualListValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualListValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualListValue}
 */
proto.SittelleProtos.ManualListValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualListValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualListValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualListValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualListValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string value = 1;
 * @return {string}
 */
proto.SittelleProtos.ManualListValue.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualListValue} returns this
 */
proto.SittelleProtos.ManualListValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string caption = 2;
 * @return {string}
 */
proto.SittelleProtos.ManualListValue.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualListValue} returns this
 */
proto.SittelleProtos.ManualListValue.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string descr = 3;
 * @return {string}
 */
proto.SittelleProtos.ManualListValue.prototype.getDescr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualListValue} returns this
 */
proto.SittelleProtos.ManualListValue.prototype.setDescr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ManualDependentValue.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualDependentValue.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualDependentValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualDependentValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualDependentValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    parentIndexListList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    valueListList: jspb.Message.toObjectList(msg.getValueListList(),
    proto.SittelleProtos.ManualListValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualDependentValue}
 */
proto.SittelleProtos.ManualDependentValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualDependentValue;
  return proto.SittelleProtos.ManualDependentValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualDependentValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualDependentValue}
 */
proto.SittelleProtos.ManualDependentValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addParentIndexList(value);
      break;
    case 2:
      var value = new proto.SittelleProtos.ManualListValue;
      reader.readMessage(value,proto.SittelleProtos.ManualListValue.deserializeBinaryFromReader);
      msg.addValueList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualDependentValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualDependentValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualDependentValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualDependentValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParentIndexListList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getValueListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SittelleProtos.ManualListValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated string parent_index_list = 1;
 * @return {!Array<string>}
 */
proto.SittelleProtos.ManualDependentValue.prototype.getParentIndexListList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.SittelleProtos.ManualDependentValue} returns this
 */
proto.SittelleProtos.ManualDependentValue.prototype.setParentIndexListList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualDependentValue} returns this
 */
proto.SittelleProtos.ManualDependentValue.prototype.addParentIndexList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualDependentValue} returns this
 */
proto.SittelleProtos.ManualDependentValue.prototype.clearParentIndexListList = function() {
  return this.setParentIndexListList([]);
};


/**
 * repeated ManualListValue value_list = 2;
 * @return {!Array<!proto.SittelleProtos.ManualListValue>}
 */
proto.SittelleProtos.ManualDependentValue.prototype.getValueListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualListValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualListValue, 2));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualListValue>} value
 * @return {!proto.SittelleProtos.ManualDependentValue} returns this
*/
proto.SittelleProtos.ManualDependentValue.prototype.setValueListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SittelleProtos.ManualListValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualListValue}
 */
proto.SittelleProtos.ManualDependentValue.prototype.addValueList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SittelleProtos.ManualListValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualDependentValue} returns this
 */
proto.SittelleProtos.ManualDependentValue.prototype.clearValueListList = function() {
  return this.setValueListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ManualRequestValue.repeatedFields_ = [11,12,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualRequestValue.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualRequestValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualRequestValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualRequestValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    ind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    caption: jspb.Message.getFieldWithDefault(msg, 3, ""),
    paramType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    valueDf: jspb.Message.getFieldWithDefault(msg, 5, ""),
    valueNull: jspb.Message.getFieldWithDefault(msg, 6, ""),
    isObligatory: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    valuesListType: jspb.Message.getFieldWithDefault(msg, 8, 0),
    maskCheck: jspb.Message.getFieldWithDefault(msg, 9, ""),
    linkInd: jspb.Message.getFieldWithDefault(msg, 10, 0),
    parentParamListList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    valueListList: jspb.Message.toObjectList(msg.getValueListList(),
    proto.SittelleProtos.ManualListValue.toObject, includeInstance),
    dependentListList: jspb.Message.toObjectList(msg.getDependentListList(),
    proto.SittelleProtos.ManualDependentValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualRequestValue}
 */
proto.SittelleProtos.ManualRequestValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualRequestValue;
  return proto.SittelleProtos.ManualRequestValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualRequestValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualRequestValue}
 */
proto.SittelleProtos.ManualRequestValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setInd(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaption(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setParamType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setValueDf(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setValueNull(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsObligatory(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setValuesListType(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaskCheck(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLinkInd(value);
      break;
    case 11:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setParentParamListList(value);
      break;
    case 12:
      var value = new proto.SittelleProtos.ManualListValue;
      reader.readMessage(value,proto.SittelleProtos.ManualListValue.deserializeBinaryFromReader);
      msg.addValueList(value);
      break;
    case 13:
      var value = new proto.SittelleProtos.ManualDependentValue;
      reader.readMessage(value,proto.SittelleProtos.ManualDependentValue.deserializeBinaryFromReader);
      msg.addDependentList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualRequestValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualRequestValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualRequestValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualRequestValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCaption();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getParamType();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getValueDf();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getValueNull();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getIsObligatory();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getValuesListType();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getMaskCheck();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getLinkInd();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getParentParamListList();
  if (f.length > 0) {
    writer.writePackedUint32(
      11,
      f
    );
  }
  f = message.getValueListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.SittelleProtos.ManualListValue.serializeBinaryToWriter
    );
  }
  f = message.getDependentListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.SittelleProtos.ManualDependentValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string caption = 3;
 * @return {string}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 param_type = 4;
 * @return {number}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getParamType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setParamType = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string value_df = 5;
 * @return {string}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getValueDf = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setValueDf = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string value_null = 6;
 * @return {string}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getValueNull = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setValueNull = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool is_obligatory = 7;
 * @return {boolean}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getIsObligatory = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setIsObligatory = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional uint32 values_list_type = 8;
 * @return {number}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getValuesListType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setValuesListType = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string mask_check = 9;
 * @return {string}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getMaskCheck = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setMaskCheck = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional uint32 link_ind = 10;
 * @return {number}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getLinkInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setLinkInd = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated uint32 parent_param_list = 11;
 * @return {!Array<number>}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getParentParamListList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.setParentParamListList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.addParentParamList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.clearParentParamListList = function() {
  return this.setParentParamListList([]);
};


/**
 * repeated ManualListValue value_list = 12;
 * @return {!Array<!proto.SittelleProtos.ManualListValue>}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getValueListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualListValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualListValue, 12));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualListValue>} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
*/
proto.SittelleProtos.ManualRequestValue.prototype.setValueListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.SittelleProtos.ManualListValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualListValue}
 */
proto.SittelleProtos.ManualRequestValue.prototype.addValueList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.SittelleProtos.ManualListValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.clearValueListList = function() {
  return this.setValueListList([]);
};


/**
 * repeated ManualDependentValue dependent_list = 13;
 * @return {!Array<!proto.SittelleProtos.ManualDependentValue>}
 */
proto.SittelleProtos.ManualRequestValue.prototype.getDependentListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualDependentValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualDependentValue, 13));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualDependentValue>} value
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
*/
proto.SittelleProtos.ManualRequestValue.prototype.setDependentListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.SittelleProtos.ManualDependentValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualDependentValue}
 */
proto.SittelleProtos.ManualRequestValue.prototype.addDependentList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.SittelleProtos.ManualDependentValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualRequestValue} returns this
 */
proto.SittelleProtos.ManualRequestValue.prototype.clearDependentListList = function() {
  return this.setDependentListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dbTarget: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualQuery;
  return proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDbTarget(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDbTarget();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string query = 1;
 * @return {string}
 */
proto.SittelleProtos.ManualQuery.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualQuery} returns this
 */
proto.SittelleProtos.ManualQuery.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 db_target = 2;
 * @return {number}
 */
proto.SittelleProtos.ManualQuery.prototype.getDbTarget = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualQuery} returns this
 */
proto.SittelleProtos.ManualQuery.prototype.setDbTarget = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ManualParam.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualParam.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualParam.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualParam} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualParam.toObject = function(includeInstance, msg) {
  var f, obj = {
    manualRequest: (f = msg.getManualRequest()) && proto.SittelleProtos.ManualRequestValue.toObject(includeInstance, f),
    fieldIndex: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fieldCaption: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fieldDescr: jspb.Message.getFieldWithDefault(msg, 4, ""),
    queryPossibleListList: jspb.Message.toObjectList(msg.getQueryPossibleListList(),
    proto.SittelleProtos.ManualQuery.toObject, includeInstance),
    queryDependentListList: jspb.Message.toObjectList(msg.getQueryDependentListList(),
    proto.SittelleProtos.ManualQuery.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualParam}
 */
proto.SittelleProtos.ManualParam.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualParam;
  return proto.SittelleProtos.ManualParam.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualParam} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualParam}
 */
proto.SittelleProtos.ManualParam.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.SittelleProtos.ManualRequestValue;
      reader.readMessage(value,proto.SittelleProtos.ManualRequestValue.deserializeBinaryFromReader);
      msg.setManualRequest(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldIndex(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldCaption(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldDescr(value);
      break;
    case 5:
      var value = new proto.SittelleProtos.ManualQuery;
      reader.readMessage(value,proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader);
      msg.addQueryPossibleList(value);
      break;
    case 6:
      var value = new proto.SittelleProtos.ManualQuery;
      reader.readMessage(value,proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader);
      msg.addQueryDependentList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualParam.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualParam.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualParam} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualParam.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getManualRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.SittelleProtos.ManualRequestValue.serializeBinaryToWriter
    );
  }
  f = message.getFieldIndex();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFieldCaption();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFieldDescr();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getQueryPossibleListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.SittelleProtos.ManualQuery.serializeBinaryToWriter
    );
  }
  f = message.getQueryDependentListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.SittelleProtos.ManualQuery.serializeBinaryToWriter
    );
  }
};


/**
 * optional ManualRequestValue manual_request = 1;
 * @return {?proto.SittelleProtos.ManualRequestValue}
 */
proto.SittelleProtos.ManualParam.prototype.getManualRequest = function() {
  return /** @type{?proto.SittelleProtos.ManualRequestValue} */ (
    jspb.Message.getWrapperField(this, proto.SittelleProtos.ManualRequestValue, 1));
};


/**
 * @param {?proto.SittelleProtos.ManualRequestValue|undefined} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
*/
proto.SittelleProtos.ManualParam.prototype.setManualRequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.clearManualRequest = function() {
  return this.setManualRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SittelleProtos.ManualParam.prototype.hasManualRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string field_index = 2;
 * @return {string}
 */
proto.SittelleProtos.ManualParam.prototype.getFieldIndex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.setFieldIndex = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string field_caption = 3;
 * @return {string}
 */
proto.SittelleProtos.ManualParam.prototype.getFieldCaption = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.setFieldCaption = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string field_descr = 4;
 * @return {string}
 */
proto.SittelleProtos.ManualParam.prototype.getFieldDescr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.setFieldDescr = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated ManualQuery query_possible_list = 5;
 * @return {!Array<!proto.SittelleProtos.ManualQuery>}
 */
proto.SittelleProtos.ManualParam.prototype.getQueryPossibleListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualQuery>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualQuery, 5));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualQuery>} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
*/
proto.SittelleProtos.ManualParam.prototype.setQueryPossibleListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.SittelleProtos.ManualQuery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualParam.prototype.addQueryPossibleList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.SittelleProtos.ManualQuery, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.clearQueryPossibleListList = function() {
  return this.setQueryPossibleListList([]);
};


/**
 * repeated ManualQuery query_dependent_list = 6;
 * @return {!Array<!proto.SittelleProtos.ManualQuery>}
 */
proto.SittelleProtos.ManualParam.prototype.getQueryDependentListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualQuery>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualQuery, 6));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualQuery>} value
 * @return {!proto.SittelleProtos.ManualParam} returns this
*/
proto.SittelleProtos.ManualParam.prototype.setQueryDependentListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.SittelleProtos.ManualQuery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualParam.prototype.addQueryDependentList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.SittelleProtos.ManualQuery, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualParam} returns this
 */
proto.SittelleProtos.ManualParam.prototype.clearQueryDependentListList = function() {
  return this.setQueryDependentListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ManualTaskType.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualTaskType.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualTaskType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualTaskType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualTaskType.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskTypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    paramListList: jspb.Message.toObjectList(msg.getParamListList(),
    proto.SittelleProtos.ManualParam.toObject, includeInstance),
    queryApplyListList: jspb.Message.toObjectList(msg.getQueryApplyListList(),
    proto.SittelleProtos.ManualQuery.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualTaskType}
 */
proto.SittelleProtos.ManualTaskType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualTaskType;
  return proto.SittelleProtos.ManualTaskType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualTaskType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualTaskType}
 */
proto.SittelleProtos.ManualTaskType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskTypeInd(value);
      break;
    case 2:
      var value = new proto.SittelleProtos.ManualParam;
      reader.readMessage(value,proto.SittelleProtos.ManualParam.deserializeBinaryFromReader);
      msg.addParamList(value);
      break;
    case 3:
      var value = new proto.SittelleProtos.ManualQuery;
      reader.readMessage(value,proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader);
      msg.addQueryApplyList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualTaskType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualTaskType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualTaskType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualTaskType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTaskTypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getParamListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SittelleProtos.ManualParam.serializeBinaryToWriter
    );
  }
  f = message.getQueryApplyListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.SittelleProtos.ManualQuery.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 task_type_ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ManualTaskType.prototype.getTaskTypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualTaskType} returns this
 */
proto.SittelleProtos.ManualTaskType.prototype.setTaskTypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated ManualParam param_list = 2;
 * @return {!Array<!proto.SittelleProtos.ManualParam>}
 */
proto.SittelleProtos.ManualTaskType.prototype.getParamListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualParam>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualParam, 2));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualParam>} value
 * @return {!proto.SittelleProtos.ManualTaskType} returns this
*/
proto.SittelleProtos.ManualTaskType.prototype.setParamListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SittelleProtos.ManualParam=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualParam}
 */
proto.SittelleProtos.ManualTaskType.prototype.addParamList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SittelleProtos.ManualParam, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualTaskType} returns this
 */
proto.SittelleProtos.ManualTaskType.prototype.clearParamListList = function() {
  return this.setParamListList([]);
};


/**
 * repeated ManualQuery query_apply_list = 3;
 * @return {!Array<!proto.SittelleProtos.ManualQuery>}
 */
proto.SittelleProtos.ManualTaskType.prototype.getQueryApplyListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualQuery>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualQuery, 3));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualQuery>} value
 * @return {!proto.SittelleProtos.ManualTaskType} returns this
*/
proto.SittelleProtos.ManualTaskType.prototype.setQueryApplyListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.SittelleProtos.ManualQuery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualTaskType.prototype.addQueryApplyList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.SittelleProtos.ManualQuery, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualTaskType} returns this
 */
proto.SittelleProtos.ManualTaskType.prototype.clearQueryApplyListList = function() {
  return this.setQueryApplyListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SittelleProtos.ManualQueryApplyTaskType.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.toObject = function(opt_includeInstance) {
  return proto.SittelleProtos.ManualQueryApplyTaskType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SittelleProtos.ManualQueryApplyTaskType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualQueryApplyTaskType.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskTypeInd: jspb.Message.getFieldWithDefault(msg, 1, 0),
    queryApplyListList: jspb.Message.toObjectList(msg.getQueryApplyListList(),
    proto.SittelleProtos.ManualQuery.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SittelleProtos.ManualQueryApplyTaskType}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SittelleProtos.ManualQueryApplyTaskType;
  return proto.SittelleProtos.ManualQueryApplyTaskType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SittelleProtos.ManualQueryApplyTaskType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SittelleProtos.ManualQueryApplyTaskType}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskTypeInd(value);
      break;
    case 3:
      var value = new proto.SittelleProtos.ManualQuery;
      reader.readMessage(value,proto.SittelleProtos.ManualQuery.deserializeBinaryFromReader);
      msg.addQueryApplyList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SittelleProtos.ManualQueryApplyTaskType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SittelleProtos.ManualQueryApplyTaskType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SittelleProtos.ManualQueryApplyTaskType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTaskTypeInd();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getQueryApplyListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.SittelleProtos.ManualQuery.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 task_type_ind = 1;
 * @return {number}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.getTaskTypeInd = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SittelleProtos.ManualQueryApplyTaskType} returns this
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.setTaskTypeInd = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated ManualQuery query_apply_list = 3;
 * @return {!Array<!proto.SittelleProtos.ManualQuery>}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.getQueryApplyListList = function() {
  return /** @type{!Array<!proto.SittelleProtos.ManualQuery>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SittelleProtos.ManualQuery, 3));
};


/**
 * @param {!Array<!proto.SittelleProtos.ManualQuery>} value
 * @return {!proto.SittelleProtos.ManualQueryApplyTaskType} returns this
*/
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.setQueryApplyListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.SittelleProtos.ManualQuery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SittelleProtos.ManualQuery}
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.addQueryApplyList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.SittelleProtos.ManualQuery, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SittelleProtos.ManualQueryApplyTaskType} returns this
 */
proto.SittelleProtos.ManualQueryApplyTaskType.prototype.clearQueryApplyListList = function() {
  return this.setQueryApplyListList([]);
};


goog.object.extend(exports, proto.SittelleProtos);
